In [1]:
import pandas as pd
import numpy as np

In [2]:
mental_health = pd.read_csv('mental_health.csv')

In [3]:
mental_health

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,49,Female,Employed,4.8,4.0,1,8.0,1,9.8,Medium,5,0,1,1,1,0,0
1996,1997,33,Male,Employed,2.7,2.6,0,7.2,9,10.1,Low,8,1,1,1,1,1,1
1997,1998,28,Male,Employed,2.6,4.6,0,6.5,10,7.7,Medium,6,2,0,0,0,1,1
1998,1999,56,Female,Student,3.2,2.8,1,8.3,9,2.1,High,5,0,1,1,0,0,0
1999,2000,38,Male,Unemployed,7.8,7.6,0,7.2,7,9.6,Low,1,3,0,1,1,0,1

In [6]:
mental_health[mental_health['Daily_Screen_Time'] >0.0].groupby('Occupation').min()

,Person_ID,Age,Gender,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
Occupation,,,,,,,,,,,,,,,,,
Employed,3,16,Female,2.0,1.0,0,3.0,1,2.0,High,1,0,0,0,0,0,0
Student,1,16,Female,2.0,1.0,0,3.0,1,2.0,High,1,0,0,0,0,0,0
Unemployed,7,16,Female,2.1,1.0,0,3.0,1,2.0,High,1,0,0,0,0,0,0