In [101]:
import pandas as pd
import numpy as np

In [68]:
movies = pd.read_csv('imdb-top-1000.csv')

In [69]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [70]:
#groupby -> catagory
genres =movies.groupby('Genre')
genres

In [71]:
genres.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [72]:
#find top 3 genres by total earning

movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [73]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [74]:
movies.groupby('Director')['Gross'].sum().sort_values(ascending=False).head(3)

Director
Akira Kurosawa      3.070432e+09
Steven Spielberg    2.478133e+09
Hayao Miyazaki      2.447325e+09
Name: Gross, dtype: float64

In [75]:
# find the genre with highest avg IMDB rating

movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(3)

Genre
Western    8.350000
Crime      8.016822
Fantasy    8.000000
Name: IMDB_Rating, dtype: float64

In [76]:
# find the genre with highest IMDB rating

movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(3)

Genre
Drama     9.3
Crime     9.2
Action    9.0
Name: IMDB_Rating, dtype: float64

In [77]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [78]:
movies.groupby('Director')['Metascore'].sum().sort_values(ascending=False).head(3)

Director
Alfred Hitchcock    1270.0
Steven Spielberg    1047.0
Hayao Miyazaki       908.0
Name: Metascore, dtype: float64

In [79]:
# find the highest rated movie of each genre

max_ratings = movies.groupby('Genre')['IMDB_Rating'].transform('max')

all_top_movies = movies[movies['IMDB_Rating'] == max_ratings]

all_top_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [80]:
 #find number of movies done by each actor

movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [81]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [82]:
len(movies.groupby('Genre'))

14

In [83]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [84]:
genres.nth(100)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
319,Sunrise: A Song of Two Humans,1927,94,Drama,8.1,F.W. Murnau,George O'Brien,46865,539540.0,NaN
625,Apocalypto,2006,139,Action,7.8,Mel Gibson,Gerardo Taracena,291018,50866635.0,68.0
704,Mary Poppins,1964,139,Comedy,7.8,Robert Stevenson,Julie Andrews,158029,102272727.0,88.0
939,Boksuneun naui geot,2002,129,Crime,7.6,Chan-wook Park,Kang-ho Song,62659,45289.0,56.0

In [85]:
genres = movies.groupby('Genre')

In [86]:
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [87]:
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [88]:
genres.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [89]:
genres.get_group('Fantasy') #fast

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [90]:
movies[movies['Genre'] == 'Fantasy']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [91]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [92]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [93]:
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
362,The Bourne Ultimatum,2007,115,Action,8.0,Paul Greengrass,Matt Damon,604694,227471070.0,85.0
356,Tropa de Elite,2007,115,Action,8.0,José Padilha,Wagner Moura,98097,8060.0,33.0
513,Children of Men,2006,109,Adventure,7.9,Alfonso Cuarón,Julianne Moore,465113,35552383.0,84.0
537,La montaña sagrada,1973,114,Adventure,7.9,Alejandro Jodorowsky,Alejandro Jodorowsky,37183,61001.0,76.0
875,Fantasia,1940,125,Animation,7.7,James Algar,Samuel Armstrong,88662,76408097.0,96.0
694,La planète sauvage,1973,72,Animation,7.8,René Laloux,Barry Bostwick,25229,193817.0,73.0
858,A Man for All Seasons,1966,120,Biography,7.7,Fred Zinnemann,Paul Scofield,31222,28350000.0,72.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
471,Captain Fantastic,2016,118,Comedy,7.9,Matt Ross,Viggo Mortensen,189400,5875006.0,72.0
494,In Bruges,2008,107,Comedy,7.9,Martin McDonagh,Colin Farrell,390334,7757130.0,67.0
363,Bin-jip,2004,88,Crime,8.0,Ki-duk Kim,Seung-Yun Lee,50610,238507.0,72.0
723,Wind River,2017,107,Crime,7.7,Taylor Sheridan,Kelsey Asbille,205444,33800859.0,73.0
350,Dev.D,2009,144,Drama,8.0,Anurag Kashyap,Abhay Deol,28749,10950.0,NaN
148,Chak De! India,2007,153,Drama,8.2,Shimit Amin,Shah Rukh Khan,74129,1113541.0,68.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [94]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [95]:
#agg method 
#passing dict
genres.agg(
    {
        'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Metascore':'mean'
    }
)

              Runtime  IMDB_Rating  No_of_Votes  Metascore
Genre
Action     129.046512     7.949419     72282412  73.419580
Adventure  134.111111     7.937500     22576163  78.437500
Animation   99.585366     7.930488     21978630  81.093333
Biography  136.022727     7.938636     24006844  76.240506
Comedy     112.129032     7.901290     27620327  78.720000
Crime      126.392523     8.016822     33533615  77.080460
Drama      124.737024     7.957439     61367304  79.701245
Family     107.500000     7.800000       551221  79.000000
Fantasy     85.000000     8.000000       146222        NaN
Film-Noir  104.000000     7.966667       367215  95.666667
Horror     102.090909     7.909091      3742556  80.000000
Mystery    119.083333     7.975000      4203004  79.125000
Thriller   108.000000     7.800000        27733  81.000000
Western    148.250000     8.350000      1289665  78.250000

In [96]:
#passing list 
genres.agg(['min', 'max', 'count'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                     Released_Year        \
                                           max count           min   max
Genre
Action                                 Yôjinbô   172          1924  2019
Adventure                           Zombieland    72          1925    PG
Animation          Ôkami kodomo no Ame to Yuki    82          1940  2020
Biography                              Zerkalo    88          1928  2020
Comedy                Zindagi Na Milegi Dobara   155          1921  2020
Crime                        À bout de souffle   107          1931  2019
Drama                                Zwartboek   289          1925  2020
Family     Willy Wonka & the Chocolate Factory     2          1971  1982
Fantasy                              Nosferatu     2          1920  1922
Film-Noir                        The Third Man     3          1941  1949
Horror                               The Thing    11          1933  2017
Mystery                                Vertigo    12          1938  2012
Thriller                       Wait Until Dark     1          1967  1967
Western                 The Outlaw Josey Wales     4          1965  1976

                Runtime            IMDB_Rating  ... Star1 No_of_Votes  \
          count     min  max count         min  ... count         min
Genre                                           ...
Action      172      45  321   172         7.6  ...   172       25312
Adventure    72      88  228    72         7.6  ...    72       29999
Animation    82      71  137    82         7.6  ...    82       25229
Biography    88      93  209    88         7.6  ...    88       27254
Comedy      155      68  188   155         7.6  ...   155       26337
Crime       107      80  229   107         7.6  ...   107       27712
Drama       289      64  242   289         7.6  ...   289       25088
Family        2     100  115     2         7.8  ...     2      178731
Fantasy       2      76   94     2         7.9  ...     2       57428
Film-Noir     3     100  108     3         7.8  ...     3       59556
Horror       11      71  122    11         7.6  ...    11       27007
Mystery      12      96  138    12         7.6  ...    12       33982
Thriller      1     108  108     1         7.8  ...     1       27733
Western       4     132  165     4         7.8  ...     4       65659

                                Gross                    Metascore         \
               max count          min          max count       min    max
Genre
Action     2303232   172       3296.0  936662225.0   172      33.0   98.0
Adventure  1512360    72      61001.0  874211619.0    72      41.0  100.0
Animation   999790    82     128985.0  873839108.0    82      61.0   96.0
Biography  1213505    88      21877.0  753585104.0    88      48.0   97.0
Comedy      939631   155       1305.0  886752933.0   155      45.0   99.0
Crime      1826188   107       6013.0  790482117.0   107      47.0  100.0
Drama      2343110   289       3600.0  924558264.0   289      28.0  100.0
Family      372490     2    4000000.0  435110554.0     2      67.0   91.0
Fantasy      88794     2  337574718.0  445151978.0     2       NaN    NaN
Film-Noir   158731     3     449191.0  123353292.0     3      94.0   97.0
Horror      787806    11      89029.0  298791505.0    11      46.0   97.0
Mystery    1129894    12    1035953.0  474203697.0    12      52.0  100.0
Thriller     27733     1   17550741.0   17550741.0     1      81.0   81.0
Western     688390     4    5321508.0   31800000.0     4      69.0   90.0


          count
Genre
Action      143
Adventure    64
Animation    75
Biography    79
Comedy      125
Crime        87
Drama       241
Family        2
Fantasy       0
Film-Noir     3
Horror       11
Mystery       8
Thriller      1
Western       4

[14 rows x 27 columns]

In [97]:
#agg method 
#passing dict
#adding both the syntax

genres.agg(
    {
        'Runtime':['mean','min'],
        'IMDB_Rating':['mean','min'],
        'No_of_Votes':['sum','max'],
        'Metascore':'mean'
    }
)

              Runtime      IMDB_Rating      No_of_Votes           Metascore
                 mean  min        mean  min         sum      max       mean
Genre
Action     129.046512   45    7.949419  7.6    72282412  2303232  73.419580
Adventure  134.111111   88    7.937500  7.6    22576163  1512360  78.437500
Animation   99.585366   71    7.930488  7.6    21978630   999790  81.093333
Biography  136.022727   93    7.938636  7.6    24006844  1213505  76.240506
Comedy     112.129032   68    7.901290  7.6    27620327   939631  78.720000
Crime      126.392523   80    8.016822  7.6    33533615  1826188  77.080460
Drama      124.737024   64    7.957439  7.6    61367304  2343110  79.701245
Family     107.500000  100    7.800000  7.8      551221   372490  79.000000
Fantasy     85.000000   76    8.000000  7.9      146222    88794        NaN
Film-Noir  104.000000  100    7.966667  7.8      367215   158731  95.666667
Horror     102.090909   71    7.909091  7.6     3742556   787806  80.000000
Mystery    119.083333   96    7.975000  7.6     4203004  1129894  79.125000
Thriller   108.000000  108    7.800000  7.8       27733    27733  81.000000
Western    148.250000  132    8.350000  7.8     1289665   688390  78.250000

In [98]:
df = pd.DataFrame(columns = movies.columns)
for group,data in genres:
    df.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
#split (apply) combine 
#apply -> buit in function

genres.apply(min)

In [ ]:
genres.min()

In [ ]:
# looping on groups
results = []
for group,data in genres:
    highest_rated = data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]
    results.append(highest_rated)

df = pd.concat(results, ignore_index=True)
df

In [ ]:
# looping of group
df = pd.DataFrame(columns=movies.columns)
print(df)
for group,data in genres:
    df = df.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

df

In [ ]:
genres.get_group('Horror')

In [ ]:
combo_group = movies.groupby(['Director','Star1'])
combo_group.size()

In [ ]:
genres.get_group('Fantasy')

In [ ]:
genres.groups

In [ ]:
genres.describe()

In [ ]:
genres.sample(1)

In [ ]:
genres.nunique()

In [ ]:
# how to use loop
top_movies = []
df = pd.DataFrame(columns=movies.columns)
print(df)
for group,data in genres:
    best_movie = data[data['IMDB_Rating'] ==  data['IMDB_Rating'].max()]
    top_movies.append(best_movie)
    
    df = pd.concat(top_movies,ignore_index=True)

df

In [ ]:
#split apply combine
#apply -> builtin functions 

genres.apply(max)

In [ ]:
genres = movies.groupby('Genre')
genres.apply(min)

In [ ]:
def foo (group):
    print(group)
    return group

genres.apply(foo)

In [ ]:
def foo (group):    
    return group['Series_Title'].str.startswith("A").sum()    

genres.apply(foo)

In [ ]:
def ranking_movie(group):
    group['IMDB_Rating'] = group['IMDB_Rating'].rank(ascending=False)
    return group

In [ ]:
genres.apply(ranking_movie)

In [ ]:
def normal(group):
    group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min()) / (group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
    return group

genres.apply(normal)


#apply custome logic apply

In [ ]:
#group on multiple colums 
duo = movies.groupby(['Director','Star1'])
duo.size()

In [ ]:
duo.get_group(('Aaron Sorkin','Eddie Redmayne'))
duo['Gross'].sum().sort_values(ascending=False).head(1)

In [ ]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False)

In [ ]:
duo.agg(['min','max'])

In [102]:
ipl = pd.read_csv('deliveries.csv')
ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [103]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  str
 3   bowling_team      179078 non-null  str
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  str
 7   non_striker       179078 non-null  str
 8   bowler            179078 non-null  str
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    str
 19  dismissal_kind    8834 non-null    str
 20  fielder           6448 non-null    str
dtypes: int64(13), str(8)
memory usage: 39.9 MB

In [ ]:
ipl.shape

In [104]:
#find top 10 batsman in terms of run

ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [106]:
six_runs = ipl[ipl['batsman_runs'] == 6]

In [107]:
six_runs.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
CK Langeveldt       1
JDS Neesham         1
SK Trivedi          1
D Shorey            1
MN van Wyk          1
Name: batsman, Length: 336, dtype: int64

In [108]:
last_over = ipl[ipl['over'] > 15]
last_over[(last_over['batsman_runs'] ==4 ) | (last_over['batsman_runs'] == 6)]
last_over.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
MS Dhoni          1548
KA Pollard         967
RG Sharma          818
YK Pathan          732
RA Jadeja          707
                  ...
NJ Rimmington        1
V Pratap Singh       1
Sunny Gupta          1
A Mukund             1
DT Patil             1
Name: batsman, Length: 465, dtype: int64

In [116]:
# find V kohli's record against all team
temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [127]:
#creates a function that can return the highest score of any batsman

temp_df = ipl[ipl['batsman'] == 'MS Dhoni']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)

match_id
11330    89
Name: batsman_runs, dtype: int64

In [126]:
def highest_score (batsman):
    temp_df = ipl[ipl['batsman'] == 'batsman']
    temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

highest_score('MS Dhoni')

IndexError: index 0 is out of bounds for axis 0 with size 0