In [21]:
import pandas as pd
import numpy as np

In [3]:
student = pd.read_csv('StudentsPerformance.csv')

In [4]:
student

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
student.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
student.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

In [14]:
student.groupby("gender")["math score"].mean()

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

In [24]:
student[['math score','reading score','writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [33]:
student['total'] = student[['math score','reading score','writing score']].sum(axis=1)

topper = student.sort_values(by='total',ascending=False)

topper.head(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
916,male,group E,bachelor's degree,standard,completed,100,100,100,300

In [36]:
#Find the topper (highest math score)

student.sort_values(by='math score',ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
962,female,group E,associate's degree,standard,none,100,100,100,300
625,male,group D,some college,standard,completed,100,97,99,296
458,female,group E,bachelor's degree,standard,none,100,100,100,300
623,male,group A,some college,standard,completed,100,96,86,282
451,female,group E,some college,standard,none,100,92,97,289
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,94
787,female,group B,some college,standard,none,19,38,32,89
17,female,group B,some high school,free/reduced,none,18,32,28,78
980,female,group B,high school,free/reduced,none,8,24,23,55
59,female,group C,some high school,free/reduced,none,0,17,10,27

In [39]:
student[student['math score']>90]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
34,male,group E,some college,standard,none,97,87,82,266
104,male,group C,some college,standard,completed,98,86,90,274
114,female,group E,bachelor's degree,standard,completed,99,100,100,299
121,male,group B,associate's degree,standard,completed,91,89,92,272
149,male,group E,associate's degree,free/reduced,completed,100,100,93,293
165,female,group C,bachelor's degree,standard,completed,96,100,100,296
171,male,group E,some high school,standard,none,94,88,78,260
179,female,group D,some high school,standard,completed,97,100,100,297
233,male,group E,some high school,standard,none,92,87,78,257
263,female,group E,high school,standard,none,99,93,90,282
286,male,group E,associate's degree,standard,completed,97,82,88,267
306,male,group E,some college,standard,completed,99,87,81,267
451,female,group E,some college,standard,none,100,92,97,289
458,female,group E,bachelor's degree,standard,none,100,100,100,300
469,male,group C,some college,standard,none,91,74,76,241
501,female,group B,associate's degree,standard,completed,94,87,92,273
503,female,group E,associate's degree,standard,completed,95,89,92,276
521,female,group C,associate's degree,standard,none,91,86,84,261
539,male,group A,associate's degree,standard,completed,97,92,86,275
546,female,group A,some high school,standard,completed,92,100,97,289
562,male,group C,bachelor's degree,standard,completed,96,90,92,278
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100,292
571,male,group A,bachelor's degree,standard,none,91,96,92,279
594,female,group C,bachelor's degree,standard,completed,92,100,99,291
612,male,group C,bachelor's degree,standard,completed,94,90,91,275
618,male,group D,master's degree,standard,none,95,81,84,260
623,male,group A,some college,standard,completed,100,96,86,282
625,male,group D,some college,standard,completed,100,97,99,296
685,female,group E,master's degree,standard,completed,94,99,100,293
689,male,group E,some college,free/reduced,none,93,90,83,266
710,male,group C,some college,standard,completed,93,84,90,267
712,female,group D,some college,standard,none,98,100,99,297
717,female,group C,associate's degree,standard,completed,96,96,99,291
719,male,group E,associate's degree,free/reduced,completed,91,73,80,244
736,male,group C,associate's degree,standard,none,92,79,84,255
779,male,group E,associate's degree,standard,completed,94,85,82,261
784,male,group C,bachelor's degree,standard,completed,91,81,79,251
815,male,group B,some high school,standard,completed,94,86,87,267
846,male,group C,master's degree,standard,completed,91,85,85,261
855,female,group B,bachelor's degree,standard,none,97,97,96,290
864,male,group C,associate's degree,standard,none,97,93,91,281
886,female,group E,associate's degree,standard,completed,93,100,95,288
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100,293
916,male,group E,bachelor's degree,standard,completed,100,100,100,300
919,male,group B,some college,standard,completed,91,96,91,278
934,male,group C,associate's degree,standard,completed,98,87,90,275
950,male,group E,high school,standard,none,94,73,71,238
957,female,group D,master's degree,standard,none,92,100,100,292
962,female,group E,associate's degree,standard,none,100,100,100,300
979,female,group C,associate's degree,standard,none,91,95,94,280

In [41]:
student

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [50]:
student[student['total']>250].groupby('race/ethnicity').max()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
race/ethnicity,,,,,,,,
group A,male,some high school,standard,none,100,100,97,289
group B,male,some high school,standard,none,97,97,96,290
group C,male,some high school,standard,none,98,100,100,296
group D,male,some high school,standard,none,100,100,100,297
group E,male,some high school,standard,none,100,100,100,300

In [51]:
student[student['total']>250].groupby('race/ethnicity').min()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
race/ethnicity,,,,,,,,
group A,female,associate's degree,standard,completed,78,84,86,256
group B,female,associate's degree,free/reduced,completed,74,84,84,251
group C,female,associate's degree,free/reduced,completed,77,79,79,251
group D,female,associate's degree,free/reduced,completed,74,81,75,251
group E,female,associate's degree,free/reduced,completed,79,82,78,253

In [54]:
student.groupby('race/ethnicity')['total'].mean()

race/ethnicity
group A    188.977528
group B    196.405263
group C    201.394984
group D    207.538168
group E    218.257143
Name: total, dtype: float64

In [56]:
student[student['total']>250].groupby('parental level of education').max()

,gender,race/ethnicity,lunch,test preparation course,math score,reading score,writing score,total
parental level of education,,,,,,,,
associate's degree,male,group E,standard,none,100,100,100,300
bachelor's degree,male,group E,standard,none,100,100,100,300
high school,male,group E,standard,none,99,99,100,287
master's degree,male,group E,standard,none,95,100,100,293
some college,male,group E,standard,none,100,100,99,297
some high school,male,group E,standard,none,97,100,100,297

In [57]:
student[student['total']>250].groupby('parental level of education').min()

,gender,race/ethnicity,lunch,test preparation course,math score,reading score,writing score,total
parental level of education,,,,,,,,
associate's degree,female,group A,free/reduced,completed,74,79,75,251
bachelor's degree,female,group A,free/reduced,completed,77,81,79,251
high school,female,group B,standard,completed,81,87,79,255
master's degree,female,group B,free/reduced,completed,77,81,82,251
some college,female,group A,free/reduced,completed,77,81,81,251
some high school,female,group A,free/reduced,completed,74,86,78,252

In [58]:
student

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [72]:
student[student['writing score']>80].count(axis=0)

gender                         208
race/ethnicity                 208
parental level of education    208
lunch                          208
test preparation course        208
math score                     208
reading score                  208
writing score                  208
total                          208
dtype: int64

In [73]:
student.groupby('gender')['total'].mean()

gender
female    208.708494
male      197.512448
Name: total, dtype: float64